### ISSUE TITLE
adding the ebuilds to the gentoo science overlay

### ISSUE THREAD

**Issue by Jimmy2027** [aclex/pytorch-ebuild#14]
Hi @aclex, would you like to add your ebuilds to the gentoo science overlay? They could simply be proposed via a pull request. This way your ebuilds would gain visibility and support.
Also, the pytorch ebuild on the gentoo science seems to have some issues.

**Comment by aclex** [comment]
Hi, @Jimmy2027, at first, many thanks for continued interest in this repository and for the idea you've proposed!

Actually, I already happened to try to make a pull request to Gentoo Science overlay about a year ago, following a proposal to merge it there: https://github.com/gentoo/sci/pull/941 Unfortunately, during the discussion it turned out the scripts here were not going to meet high standard and all the rules of Gentoo Science overlay, so the option was to inсlude just a part of the Pytorch ebuild with quite heavy modifications. So kind of the fork of it at that moment was merged, and I made a decision to still continue supporting my own version here. Now one can choose what version to use, which is probably a good thing itself :)

I personally would be probably happy to merge it to the Gentoo Science overlay completely some time and maybe pay less time to support it, but I doubt it's possible now, with any important fixes and features I want to see in the ebuilds.

So yes, thanks again for this idea, but yes, here's how it is now)

**Comment by Jimmy2027** [comment]
Oh right, you actually are already listed as one of the maintainers of the rebuild from the science overlay. 
I was proposing a pull request with your ebuild because I saw that there are [open issues](https://github.com/gentoo/sci/issues?q=is%3Aissue+is%3Aopen+pytorch) for the ebuild in the science overlay. 
Some of them might find a solution in your ebuild, like [this one](https://github.com/gentoo/sci/issues/1070) (you have dev-util/nvidia-cuda-toolkit listed as dependency).

However, I realize that merging the two ebuilds requires a lot of effort and since both ebuilds differ substantially it makes sense to continue work on them separately :)

**Comment by aclex** [comment]
@Jimmy2027 Sorry for delayed reply, Hendrik, was a little busy this weekend.

Yes, indeed, I think, some synchronization work could be done anyway, though the list of opened issues you've mentioned doesn't look too relevant for the version in this repo. Still I'll look into it more closely.

As for the cuda-profiler thing, I don't any NVIDIA hardware to check this issue on unfortunately. Would you be able to reproduce and check, if the attached solution works, if I add it?

**Comment by Jimmy2027** [comment]
yes sure, I would be happy to test it!

**Comment by aclex** [comment]
Nice, thank you! I've uploaded the modified dependency, with the specified USE flag added, so you can test it now.

**Comment by Jimmy2027** [comment]
I just tried it out and it works fine for me!

**Comment by aclex** [comment]
Oh, nice to hear, thank you very much for trying this out!

**Comment by Jimmy2027** [comment]
Thank you for keeping this ebuild up to date! :)
