### ISSUE TITLE
doc use flag expected in IUSE for pytorch 1.13.1

### ISSUE THREAD

**Issue by ekaats** [aclex/pytorch-ebuild#19]
When installing the latest version, I eventually get an error that the doc flag is expected in IUSE. After adding it back in (I saw you actually removed it a week ago), I could emerge pytorch as expected. If need be, I can provide error logs.

Also, I saw that in the official repository the pytorch package has been added, and has been worked on recently (https://github.com/gentoo/gentoo/search?q=pytorch&type=commits). Perhaps a good time to reach out to the maintainer to see if you could contribute to the main repo as well? Looks like your ebuild has more features so they may be interested.

**Comment by aclex** [comment]
Hi, @ekaats! Thank you for pointing out, I think, I'll revert it now. There're a couple of places this flag is still used, so maybe it wasn't particularly smart from me to just remove it. Don't really remember how it's used, hope to look at it while preparing the next version.

As for the version in the official repository, yes, thank you for the link, I think I'm aware of it. It seems to be a fork of the version maintained at https://github.com/gentoo/sci/, with which we [used to discuss](https://github.com/aclex/pytorch-ebuild/issues/7) the merge previously and came to the decision of supporting both versions in parallel. That's mostly because it's quite hard to move all the features to these more official repos during the potential merge as they apparently need to be more thoroughly tested to be there. This new ebuild in the mainline Gentoo repo seems to be even more restricted, so yes, I don't think we can merge anytime soon.
