### ISSUE TITLE
PYTHON_COMPAT=( python3_{7,8,9} ) Needs updating

### ISSUE THREAD

**Issue by apcameron** [aclex/pytorch-ebuild#22]
PYTHON_COMPAT=( python3_{7,8,9} ) in Some of the ebuilds need updating to include the latest Python versions used in Gentoo

**Comment by aclex** [comment]
Thank you! That's not always possible, as older versions of packages generally need testing before adding later Python versions to compatibility list. Usually they fail to work. Hence I just remove them instead when their initial highest versions lose support in Gentoo, otherwise I try to keep them as long, as possible intact.
